[theme]
base="light"
primaryColor="#379634"
backgroundColor="#e8eddf"
textColor="#242423"
borderColor = "#379634"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]
dataframeHeaderBackgroundColor = "#CFDBD5"