[theme]
primaryColor = "#2962ff"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#212529"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
